/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a6d1ac",
        "error-container": "#ffdad6",
        "surface-container-low": "#f7f3ec",
        "on-primary-container": "#80aa86",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#a33e00",
        "inverse-surface": "#31302c",
        "outline-variant": "#c1c8bf",
        "inverse-on-surface": "#f4f0e9",
        "on-background": "#1c1c18",
        "surface-bright": "#fdf9f2",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#424941",
        "on-primary-fixed": "#00210c",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb596",
        "secondary-fixed": "#ffdbcd",
        "surface-variant": "#e6e2db",
        "outline": "#727971",
        "primary": "#00280f",
        "on-secondary-container": "#672400",
        "surface-container": "#f1ede6",
        "secondary-container": "#ff7e41",
        "surface-container-highest": "#e6e2db",
        "surface": "#fdf9f2",
        "surface-dim": "#dddad3",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#202220",
        "primary-container": "#173e23",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#7d2d00",
        "tertiary-container": "#363735",
        "inverse-primary": "#a6d1ac",
        "on-tertiary": "#ffffff",
        "background": "#fdf9f2",
        "surface-container-high": "#ebe8e1",
        "on-tertiary-fixed": "#1a1c1a",
        "on-primary-fixed-variant": "#284f32",
        "tertiary-fixed-dim": "#c7c6c4",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#360f00",
        "primary-fixed": "#c1eec6",
        "tertiary-fixed": "#e3e2e0",
        "on-tertiary-fixed-variant": "#464745",
        "on-tertiary-container": "#a0a09d",
        "surface-tint": "#406748",
        "brand-green": "#173E23",
        "brand-orange": "#C65518",
        "brand-obsidian": "#173E23",
        "brand-cream": "#FAFAF8",
        "brand-ivory": "#F2EFE6",
        "ink-green": "#173E23",
        "ink-orange": "#C65518",
        "paper": "#FAFAF8",
        "paper-alt": "#F2EFE6",
        "ink-text": "#1A1A1A",
        "primary-green": "#173E23",
        "primary-orange": "#C65518",
        "canvas": "#FAFAF8",
        "canvas-alt": "#F2EFE6",
        "charcoal": "#1A1A1A",
        "hairline": "#E5E5E0",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xl": "3rem",
        "margin-desktop": "3.5rem",
        "space-xl": "2rem",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "gutter-desktop": "2rem",
        "space-2xs": "0.25rem",
        "space-3xl": "4.5rem",
        "space-sm": "0.75rem"
      },
      fontFamily: {
        "sketch": ['"Caveat"', 'cursive'],
        "display": ['"Bebas Neue"', 'sans-serif'],
        "serif": ['"Playfair Display"', 'serif'],
        "script": ['"Caveat"', 'cursive'],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "label-editorial": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-lg-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-editorial": ["11px", { "lineHeight": "16px", "letterSpacing": "0.14em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "body-lg": ["17px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
