/**
 * Curated Fallback Data for Food Tailor (Hyderabad Atelier Guild)
 * Exactly the 11 Officially Approved Master Brands & Dishes.
 */

export const FALLBACK_PARTNERS = [
  {
    id: 'ptr_niloufer',
    slug: 'cafe-niloufer',
    businessName: 'Cafe Niloufer',
    logoUrl: '/brands/cafe-niloufer.png',
    cuisine: 'Irani & Bakery',
    location: 'Lakdikapul / Banjara Hills, Hyderabad',
    description: "Since 1978, Cafe Niloufer has defined Hyderabad's quintessential Irani chai and artisanal bakery culture with scalded whole-milk chai, bun maska, and double-baked Osmania biscuits.",
    coverImageUrl: '/dishes/cafe-niloufer-chai-bun.jpg',
    established: 1978,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 2500,
    maxEventCapacity: 100,
    tagline: 'Wahi swad, ek naya andaaz — Since 1978',
    whyWePicked: 'Quintessential Hyderabadi afternoon gathering tea and biscuit institution with uncompromised whole milk freshness.',
  },
  {
    id: 'ptr_shadab',
    slug: 'hotel-shadab',
    businessName: 'Hotel Shadab',
    cuisine: 'Hyderabadi & Mughlai',
    location: 'Ghansi Bazaar / Old City, Hyderabad',
    description: 'Near the historic Charminar since 1953, producing legendary slow-cooked Nizami Dum Biryanis, Tandoori Starters, Shahi Haleem, and Nahari.',
    coverImageUrl: '/dishes/shadab-kaju-paneer-biryani.png',
    established: 1953,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 5000,
    maxEventCapacity: 100,
    tagline: 'The Taste of Hyderabad — India | UAE',
    whyWePicked: 'Old City royalty with 70+ years of unyielding master-degh consistency and saffron layering.',
  },
  {
    id: 'ptr_samosasingh',
    slug: 'samosa-king',
    businessName: 'Samosa King',
    cuisine: 'Appetizers & Snacks',
    location: 'Hitec City / Gachibowli, Hyderabad',
    description: "Reinventing India's favorite snack with golden handcrafted cocktail samosas, signature mint chutney, and seasonal fillings.",
    coverImageUrl: '/dishes/samosa-king-gourmet.jpg',
    established: 2016,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 1800,
    maxEventCapacity: 100,
    tagline: 'Crispy, Golden Handcrafted Gourmet Samosas',
    whyWePicked: 'Ultra-crisp cocktail starters that retain textural integrity for party gatherings.',
  },
  {
    id: 'ptr_thickshake',
    slug: 'thick-shake-factory',
    businessName: 'Thick Shake Factory',
    cuisine: 'Beverages & Shakes',
    location: 'Banjara Hills / Hitec City, Hyderabad',
    description: "Specialty thick shake house crafting ultra-dense, velvety thick shakes from pure Belgian chocolate, Alphonso mangoes, and boba pearls.",
    coverImageUrl: '/dishes/thick-shake-boba.jpg',
    established: 2013,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 100,
    tagline: 'Rich, Decadent Shakes & Coolers',
    whyWePicked: 'Crowd-pleasing beverage stations adored by younger guests and party attendees.',
  },
  {
    id: 'ptr_iceberg',
    slug: 'ice-berg',
    businessName: 'Ice Berg',
    cuisine: 'Desserts & Ice Creams',
    location: 'Jubilee Hills / Madhapur, Hyderabad',
    description: 'Organic handcrafted ice creams made with real seasonal fruits like Sitaphal, tender coconut, and Belgian dark chocolate.',
    coverImageUrl: '/dishes/ice-berg-gelato-cup.jpg',
    established: 2012,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 100,
    tagline: 'Artisanal Natural Rolled Scoops',
    whyWePicked: 'Pure fruit, preservative-free artisanal ice creams offering the ultimate refreshing dessert station.',
  },
  {
    id: 'ptr_maharaja',
    slug: 'maharaja-chaat',
    businessName: 'Maharaja Chaat',
    cuisine: 'Street Food & Chaat',
    location: 'Road No. 36, Jubilee Hills, Hyderabad',
    description: 'Hyderabad’s gold standard for live Pani Puri bars, Dahi Puri platters, and sizzling Sev Batata Puri counters.',
    coverImageUrl: '/dishes/maharaja-chaat-bowl.jpg',
    established: 1996,
    isApproved: true,
    rating: 4.7,
    minOrderAmount: 2500,
    maxEventCapacity: 100,
    tagline: 'Quality & Your Best Beverage — Since 1990',
    whyWePicked: 'Hygienic, vibrant live chaat staging with mineral water and organic chutneys.',
  },
  {
    id: 'ptr_dimmy',
    slug: 'dimmy-pan-palace',
    businessName: 'Dimmy Pan Palace',
    cuisine: 'Paan & After-Mints',
    location: 'Road No. 36, Jubilee Hills, Hyderabad',
    description: 'Hyderabad’s celebrated paan and chaat institution since 1995, crafting Meetha Paan, Belgian Chocolate Paan, and fresh seasonal juices.',
    coverImageUrl: '/dishes/dimmy-meetha-paan.jpg',
    established: 1995,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 1500,
    maxEventCapacity: 100,
    tagline: 'Chat, Juice & The Signature Royal Paan Experience',
    whyWePicked: 'The timeless, aristocratic finale essential to completing every authentic Hyderabadi banquet.',
  },
  {
    id: 'ptr_chocolateroom',
    slug: 'the-chocolate-room',
    businessName: 'The Chocolate Room',
    cuisine: 'Artisanal Confectionery',
    location: 'Road No. 10, Banjara Hills, Hyderabad',
    description: 'Bespoke dessert atelier featuring molten Belgian chocolate fondues, Italian sipping chocolates, handcrafted truffles, and warm waffle degustations.',
    coverImageUrl: '/dishes/chocolate-room-latte.jpg',
    established: 2007,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3000,
    maxEventCapacity: 100,
    tagline: 'Café & Lounge — Boutique Chocolaterie',
    whyWePicked: 'Brings theater and modern luxury dessert staging to celebrations and receptions.',
  },
  {
    id: 'ptr_almondhouse',
    slug: 'almond-house',
    businessName: 'Almond House',
    cuisine: 'Royal Indian Sweets',
    location: 'Himayatnagar / Jubilee Hills, Hyderabad',
    description: 'Master confectioners since 1989, renowned for pure ghee Gulab Jamun, Badam Halwa, Bisticks, and royal mithai.',
    coverImageUrl: '/dishes/almond-house-mithai.jpg',
    established: 1989,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3500,
    maxEventCapacity: 100,
    tagline: 'Purity, Heritage & Royal Mithai',
    whyWePicked: 'Unsurpassed pure A2 ghee purity and bespoke silver-vark presentation boxes.',
  },
  {
    id: 'ptr_manam',
    slug: 'manam-chocolate',
    businessName: 'Manam Chocolate',
    cuisine: 'Artisanal Confectionery',
    location: 'Road No. 12, Banjara Hills, Hyderabad',
    description: 'Award-winning craft chocolate atelier transforming West Godavari single-origin cacao into world-class bonbons, truffles, and tablets.',
    coverImageUrl: '/dishes/manam-craft-truffles.jpg',
    established: 2022,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3000,
    maxEventCapacity: 100,
    tagline: 'Award-Winning Single-Origin Indian Craft Cacao',
    whyWePicked: 'World-recognized bean-to-bar craftsmanship from the lush fertile delta of the Godavari.',
  },
  {
    id: 'ptr_karachi',
    slug: 'karachi-bakery',
    businessName: 'Karachi Bakery',
    cuisine: 'Irani & Bakery',
    location: 'Moazzam Jahi Market / Banjara Hills, Hyderabad',
    description: 'Founded in 1953 at Moazzam Jahi Market, Karachi Bakery is a household name worldwide for its crunchy Tutti-Frutti Fruit Biscuits and Cashew Pista cookies.',
    coverImageUrl: '/dishes/karachi-bakery-biscuits.jpg',
    established: 1953,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 100,
    tagline: 'Quality & Goodness Since 1953',
    whyWePicked: 'A timeless Hyderabad tradition that guests across generations warmly identify with.',
  },
];

export const FALLBACK_DISHES = [
  // 1. Cafe Niloufer
  {
    id: 'd_niloufer_chai',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Special Niloufer Irani Chai & Bun Maska',
    description: 'Thick, creamy, scalded whole-milk tea brewed with signature Niloufer spice blend served with warm bun maska.',
    category: 'Beverage',
    pricePerHead: 60,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/cafe-niloufer-chai-bun.jpg',
  },
  {
    id: 'd_niloufer_bun',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Fresh Bun Maska & Malai',
    description: 'Soft oven-baked buns slathered with rich homemade butter and clotted cream.',
    category: 'Starter',
    pricePerHead: 90,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/cafe-niloufer-chai-bun.jpg',
  },
  {
    id: 'd_niloufer_osmania',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Artisanal Osmania Biscuits Platter',
    description: 'Buttery, crumbly, lightly salted traditional tea biscuits baked to golden perfection.',
    category: 'Dessert',
    pricePerHead: 50,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/karachi-bakery-biscuits.jpg',
  },

  // 2. Hotel Shadab
  {
    id: 'd_shadab_kaju_paneer_biryani',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Shadab Kaju Paneer Dum Biryani',
    description: 'Royal long-grain basmati dum biryani prepared in copper handis with succulent paneer cubes, roasted golden cashews, and aromatic salan.',
    category: 'Biryani',
    pricePerHead: 240,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/shadab-kaju-paneer-biryani.png',
  },
  {
    id: 'd_shadab_chicken_tikka',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Shadab Murgh Tandoori Tikka',
    description: 'Chargrilled tender chicken tikka marinated in aromatic spices, mustard oil, and herbs, served with cooling mint chutney.',
    category: 'Starter',
    pricePerHead: 220,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/shadab-tandoori-chicken-tikka.jpg',
  },
  {
    id: 'd_shadab_mutton_biryani',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Shadab Royal Mutton Dum Biryani',
    description: 'Old City-style slow-cooked Nizami mutton biryani layered with fragrant basmati and saffron in sealed copper deghs.',
    category: 'Biryani',
    pricePerHead: 320,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/shadab-kaju-paneer-biryani.png',
  },
  {
    id: 'd_shadab_haleem',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Slow-Simmered Mutton Haleem',
    description: 'Overnight cooked broken wheat, lentils, pure ghee, and tender meat stew with fried onions and cashews.',
    category: 'Main',
    pricePerHead: 240,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/shadab-tandoori-chicken-tikka.jpg',
  },

  // 3. Samosa King
  {
    id: 'd_samosa_corn_cheese',
    partnerId: 'ptr_samosasingh',
    partnerName: 'Samosa King',
    name: 'Crispy Corn Cheese Samosa',
    description: 'Golden triangular pastry parcels filled with sweet corn and molten cheese that stay crisp for 45+ minutes.',
    category: 'Starter',
    pricePerHead: 90,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/samosa-king-gourmet.jpg',
  },
  {
    id: 'd_samosa_kheema',
    partnerId: 'ptr_samosasingh',
    partnerName: 'Samosa King',
    name: 'Hyderabadi Spiced Kheema Samosa',
    description: 'Crisp pastries stuffed with minced spiced mutton and fresh mint with tangy tamarind dip.',
    category: 'Starter',
    pricePerHead: 120,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/samosa-king-gourmet.jpg',
  },

  // 4. Thick Shake Factory
  {
    id: 'd_thickshake_chocolate',
    partnerId: 'ptr_thickshake',
    partnerName: 'Thick Shake Factory',
    name: 'Belgian Chocolate Boba Thick Shake',
    description: 'Ultra-thick gourmet chocolate shake with dark boba pearls and roasted chocolate shavings.',
    category: 'Beverage',
    pricePerHead: 150,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/thick-shake-boba.jpg',
  },

  // 5. Ice Berg
  {
    id: 'd_iceberg_sitaphal',
    partnerId: 'ptr_iceberg',
    partnerName: 'Ice Berg',
    name: 'Organic Fruit Gelato Ice Cream Trio',
    description: 'Handcrafted artisan ice cream scoops with fresh fruit pulp and crispy waffle wafer.',
    category: 'Dessert',
    pricePerHead: 120,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/ice-berg-gelato-cup.jpg',
  },

  // 6. Maharaja Chaat
  {
    id: 'd_maharaja_dahi_puri',
    partnerId: 'ptr_maharaja',
    partnerName: 'Maharaja Chaat',
    name: 'Special Dahi Papdi Chaat Platter',
    description: 'Crisp puris stuffed with spiced chickpeas, chilled sweet yogurt, golden sev, and tangy date chutney.',
    category: 'Starter',
    pricePerHead: 110,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/maharaja-chaat-bowl.jpg',
  },

  // 7. Dimmy Pan Palace
  {
    id: 'd_dimmy_meetha_pan',
    partnerId: 'ptr_dimmy',
    partnerName: 'Dimmy Pan Palace',
    name: 'Special Meetha Paan Counter',
    description: 'Fresh tender betel leaf wrapped with gulkand, fennel, cherries, and silver vark.',
    category: 'Paan',
    pricePerHead: 50,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/dimmy-meetha-paan.jpg',
  },

  // 8. The Chocolate Room
  {
    id: 'd_tcr_fondue',
    partnerId: 'ptr_chocolateroom',
    partnerName: 'The Chocolate Room',
    name: 'Belgian Sipping Chocolate & Latte Platter',
    description: 'Artisanal Italian sipping chocolate and espresso with latte art and roasted cocoa beans.',
    category: 'Dessert',
    pricePerHead: 210,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/chocolate-room-latte.jpg',
  },

  // 9. Almond House
  {
    id: 'd_almond_bisticks',
    partnerId: 'ptr_almondhouse',
    partnerName: 'Almond House',
    name: 'Signature Shahi Gulab Jamun & Mithai Bowl',
    description: 'Legendary pure ghee golden sweet balls delicately glazed in saffron syrup with pistachio slivers.',
    category: 'Dessert',
    pricePerHead: 180,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/almond-house-mithai.jpg',
  },

  // 10. Manam Chocolate
  {
    id: 'd_manam_truffles',
    partnerId: 'ptr_manam',
    partnerName: 'Manam Chocolate',
    name: 'Single Origin Craft Cacao Truffles',
    description: 'Textured artisan dark chocolate truffles made from single-origin West Godavari cacao.',
    category: 'Dessert',
    pricePerHead: 220,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/manam-craft-truffles.jpg',
  },

  // 11. Karachi Bakery
  {
    id: 'd_karachi_fruit_biscuits',
    partnerId: 'ptr_karachi',
    partnerName: 'Karachi Bakery',
    name: 'Original Karachi Fruit Biscuits',
    description: 'World-famous crunchy golden-baked round biscuits with candied fruit and cardamom essence.',
    category: 'Dessert',
    pricePerHead: 60,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: '/dishes/karachi-bakery-biscuits.jpg',
  },
];
