/**
 * Curated Fallback Data for Food Tailor (Hyderabad Atelier Guild)
 * Exactly the 11 Officially Approved Master Brands & Dishes.
 */

export const FALLBACK_PARTNERS = [
  {
    id: 'ptr_niloufer',
    slug: 'cafe-niloufer',
    businessName: 'Cafe Niloufer',
    logoUrl: '/brands/cafe-niloufer.png',
    cuisine: 'Irani & Bakery',
    location: 'Lakdikapul / Banjara Hills, Hyderabad',
    description: "Since 1978, Cafe Niloufer has defined Hyderabad's quintessential Irani chai and artisanal bakery culture with scalded whole-milk chai, bun maska, and double-baked Osmania biscuits.",
    coverImageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=1200&auto=format&fit=crop',
    established: 1978,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 2500,
    maxEventCapacity: 500,
    tagline: 'Wahi swad, ek naya andaaz — Since 1978',
    whyWePicked: 'Quintessential Hyderabadi afternoon gathering tea and biscuit institution with uncompromised whole milk freshness.',
  },
  {
    id: 'ptr_shadab',
    slug: 'hotel-shadab',
    businessName: 'Hotel Shadab',
    cuisine: 'Hyderabadi & Mughlai',
    location: 'Ghansi Bazaar / Old City, Hyderabad',
    description: 'Near the historic Charminar since 1953, producing legendary slow-cooked Nizami Mutton Dum Biryani, Shahi Haleem, and Nahari.',
    coverImageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=1200&auto=format&fit=crop',
    established: 1953,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 5000,
    maxEventCapacity: 1000,
    tagline: 'The Taste of Hyderabad — India | UAE',
    whyWePicked: 'Old City royalty with 70+ years of unyielding master-degh consistency and saffron layering.',
  },
  {
    id: 'ptr_samosasingh',
    slug: 'sammosa-singh',
    businessName: 'Samosa King',
    cuisine: 'Appetizers & Snacks',
    location: 'Hitec City / Gachibowli, Hyderabad',
    description: "Reinventing India's king of snacks with proprietary triangular pastries that stay crisp for 45+ minutes in thermal banquet carriers.",
    coverImageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1200&auto=format&fit=crop',
    established: 2016,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 1800,
    maxEventCapacity: 600,
    tagline: 'Crispy, Golden Handcrafted Gourmet Samosas',
    whyWePicked: 'Ultra-crisp cocktail starters that retain textural integrity during high-volume banquet service.',
  },
  {
    id: 'ptr_thickshake',
    slug: 'thick-shake-factory',
    businessName: 'Thick Shake Factory',
    cuisine: 'Beverages & Shakes',
    location: 'Banjara Hills / Hitec City, Hyderabad',
    description: "Specialty thick shake house crafting ultra-dense, velvety thick shakes from pure Belgian chocolate, Alphonso mangoes, and boba pearls.",
    coverImageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=1200&auto=format&fit=crop',
    established: 2013,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 500,
    tagline: 'Rich, Decadent Shakes & Coolers',
    whyWePicked: 'Crowd-pleasing beverage stations adored by younger guests and banquet attendees.',
  },
  {
    id: 'ptr_iceberg',
    slug: 'ice-berg',
    businessName: 'Ice Berg',
    cuisine: 'Desserts & Ice Creams',
    location: 'Jubilee Hills / Madhapur, Hyderabad',
    description: 'Organic handcrafted ice creams made with real seasonal fruits like Sitaphal, tender coconut, and Belgian dark chocolate.',
    coverImageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?q=80&w=1200&auto=format&fit=crop',
    established: 2012,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 500,
    tagline: 'Artisanal Natural Rolled Scoops',
    whyWePicked: 'Pure fruit, preservative-free artisanal ice creams offering the ultimate refreshing dessert station.',
  },
  {
    id: 'ptr_maharaja',
    slug: 'maharaja-chaat',
    businessName: 'Maharaja Chaat',
    cuisine: 'Street Food & Chaat',
    location: 'Road No. 36, Jubilee Hills, Hyderabad',
    description: 'Hyderabad’s gold standard for live Pani Puri bars, Dahi Puri platters, and sizzling Sev Batata Puri counters.',
    coverImageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=1200&auto=format&fit=crop',
    established: 1996,
    isApproved: true,
    rating: 4.7,
    minOrderAmount: 2500,
    maxEventCapacity: 600,
    tagline: 'Quality & Your Best Beverage — Since 1990',
    whyWePicked: 'Hygienic, vibrant live chaat staging with mineral water and organic chutneys.',
  },
  {
    id: 'ptr_dimmy',
    slug: 'dimmy-pan-palace',
    businessName: 'Dimmy Pan Palace',
    cuisine: 'Paan & After-Mints',
    location: 'Road No. 36, Jubilee Hills, Hyderabad',
    description: 'Hyderabad’s celebrated paan and chaat institution since 1995, crafting Meetha Paan, Belgian Chocolate Paan, and fresh seasonal juices.',
    coverImageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1200&auto=format&fit=crop',
    established: 1995,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 1500,
    maxEventCapacity: 1500,
    tagline: 'Chat, Juice & The Signature Royal Paan Experience',
    whyWePicked: 'The timeless, aristocratic finale essential to completing every authentic Hyderabadi banquet.',
  },
  {
    id: 'ptr_chocolateroom',
    slug: 'the-chocolate-room',
    businessName: 'The Chocolate Room',
    cuisine: 'Artisanal Confectionery',
    location: 'Road No. 10, Banjara Hills, Hyderabad',
    description: 'Bespoke dessert atelier featuring molten Belgian chocolate fondues, Italian sipping chocolates, handcrafted truffles, and warm waffle degustations.',
    coverImageUrl: 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=1200&auto=format&fit=crop',
    established: 2007,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3000,
    maxEventCapacity: 400,
    tagline: 'Café & Lounge — Boutique Chocolaterie',
    whyWePicked: 'Brings theater and modern luxury dessert staging to celebrations and receptions.',
  },
  {
    id: 'ptr_almondhouse',
    slug: 'almond-house',
    businessName: 'Almond House',
    cuisine: 'Royal Indian Sweets',
    location: 'Himayatnagar / Jubilee Hills, Hyderabad',
    description: 'Master confectioners since 1989, renowned for proprietary pure ghee Bisticks, saffron Badam Halwa, dry-fruit Kaju rolls, and Shahi sweets.',
    coverImageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=1200&auto=format&fit=crop',
    established: 1989,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3500,
    maxEventCapacity: 800,
    tagline: 'Purity, Heritage & Royal Mithai',
    whyWePicked: 'Unsurpassed pure A2 ghee purity and bespoke silver-vark presentation boxes.',
  },
  {
    id: 'ptr_manam',
    slug: 'manam-chocolate',
    businessName: 'Manam Chocolate',
    cuisine: 'Artisanal Confectionery',
    location: 'Road No. 12, Banjara Hills, Hyderabad',
    description: 'Award-winning craft chocolate atelier transforming West Godavari single-origin cacao into world-class bonbons, truffles, and tablets.',
    coverImageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=1200&auto=format&fit=crop',
    established: 2022,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3000,
    maxEventCapacity: 300,
    tagline: 'Award-Winning Single-Origin Indian Craft Cacao',
    whyWePicked: 'World-recognized bean-to-bar craftsmanship from the lush fertile delta of the Godavari.',
  },
  {
    id: 'ptr_karachi',
    slug: 'karachi-bakery',
    businessName: 'Karachi Bakery',
    cuisine: 'Irani & Bakery',
    location: 'Moazzam Jahi Market / Banjara Hills, Hyderabad',
    description: 'Founded in 1953 at Moazzam Jahi Market, Karachi Bakery is a household name worldwide for its crunchy Tutti-Frutti Fruit Biscuits and Cashew Pista cookies.',
    coverImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop',
    established: 1953,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 1000,
    tagline: 'Quality & Goodness Since 1953',
    whyWePicked: 'A timeless Hyderabad tradition that guests across generations warmly identify with.',
  },
];

export const FALLBACK_DISHES = [
  // 1. Cafe Niloufer
  {
    id: 'd_niloufer_chai',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Special Niloufer Irani Chai',
    description: 'Thick, creamy, scalded whole-milk tea brewed with signature Niloufer spice blend in traditional brass urns.',
    category: 'Beverage',
    pricePerHead: 60,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_niloufer_bun',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Fresh Bun Maska & Malai',
    description: 'Soft oven-baked buns slathered with rich homemade butter and clotted cream.',
    category: 'Starter',
    pricePerHead: 90,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_niloufer_osmania',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Artisanal Osmania Biscuits Platter',
    description: 'Buttery, crumbly, lightly salted traditional tea biscuits baked to golden perfection.',
    category: 'Dessert',
    pricePerHead: 50,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=800&auto=format&fit=crop',
  },

  // 2. Hotel Shadab
  {
    id: 'd_shadab_mutton_biryani',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Shadab Royal Mutton Dum Biryani',
    description: 'Old City-style slow-cooked Nizami mutton biryani layered with fragrant basmati and saffron in sealed copper deghs.',
    category: 'Biryani',
    pricePerHead: 320,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_shadab_chicken_biryani',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Shadab Nizami Chicken Dum Biryani',
    description: 'Aromatic chicken dum biryani slow-steamed with rich spices and caramelized onions.',
    category: 'Biryani',
    pricePerHead: 260,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_shadab_haleem',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Slow-Simmered Mutton Haleem',
    description: 'Overnight cooked broken wheat, lentils, pure ghee, and tender meat stew with fried onions and cashews.',
    category: 'Main',
    pricePerHead: 240,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
  },

  // 3. Samosa King / Sammosa Singh
  {
    id: 'd_samosa_corn_cheese',
    partnerId: 'ptr_samosasingh',
    partnerName: 'Samosa King',
    name: 'Crispy Corn Cheese Samosa',
    description: 'Golden triangular pastry parcels filled with sweet corn and molten cheese that stay crisp for 45+ minutes.',
    category: 'Starter',
    pricePerHead: 90,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_samosa_kheema',
    partnerId: 'ptr_samosasingh',
    partnerName: 'Samosa King',
    name: 'Hyderabadi Spiced Kheema Samosa',
    description: 'Crisp pastries stuffed with minced spiced mutton and fresh mint with tangy tamarind dip.',
    category: 'Starter',
    pricePerHead: 120,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
  },

  // 4. Thick Shake Factory
  {
    id: 'd_thickshake_chocolate',
    partnerId: 'ptr_thickshake',
    partnerName: 'Thick Shake Factory',
    name: 'Belgian Chocolate Thick Shake',
    description: 'Ultra-thick gourmet chocolate shake with dark fudge swirls and roasted chocolate shavings.',
    category: 'Beverage',
    pricePerHead: 150,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800&auto=format&fit=crop',
  },

  // 5. Ice Berg
  {
    id: 'd_iceberg_sitaphal',
    partnerId: 'ptr_iceberg',
    partnerName: 'Ice Berg',
    name: 'Organic Fresh Sitaphal Scoop',
    description: 'Handcrafted ice cream with real custard apple pulp and tender coconut malai.',
    category: 'Dessert',
    pricePerHead: 120,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?q=80&w=800&auto=format&fit=crop',
  },

  // 6. Maharaja Chaat
  {
    id: 'd_maharaja_dahi_puri',
    partnerId: 'ptr_maharaja',
    partnerName: 'Maharaja Chaat',
    name: 'Special Dahi Puri Platter',
    description: 'Crisp puris stuffed with spiced potatoes, chilled sweet yogurt, sev, and tangy date chutney.',
    category: 'Starter',
    pricePerHead: 110,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop',
  },

  // 7. Dimmy Pan Palace
  {
    id: 'd_dimmy_meetha_pan',
    partnerId: 'ptr_dimmy',
    partnerName: 'Dimmy Pan Palace',
    name: 'Special Meetha Paan Counter',
    description: 'Fresh tender betel leaf wrapped with gulkand, fennel, cherries, and silver vark.',
    category: 'Paan',
    pricePerHead: 50,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
  },

  // 8. The Chocolate Room
  {
    id: 'd_tcr_fondue',
    partnerId: 'ptr_chocolateroom',
    partnerName: 'The Chocolate Room',
    name: 'Belgian Chocolate Fondue Platter',
    description: 'Warm molten Belgian chocolate served with fresh fruit skewers, brownies, and marshmallows.',
    category: 'Dessert',
    pricePerHead: 210,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=800&auto=format&fit=crop',
  },

  // 9. Almond House
  {
    id: 'd_almond_bisticks',
    partnerId: 'ptr_almondhouse',
    partnerName: 'Almond House',
    name: 'Signature Almond Bisticks',
    description: 'Legendary crunchy almond confectionery exclusive to Almond House.',
    category: 'Dessert',
    pricePerHead: 180,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop',
  },

  // 10. Manam Chocolate
  {
    id: 'd_manam_truffles',
    partnerId: 'ptr_manam',
    partnerName: 'Manam Chocolate',
    name: 'Single Origin Cacao Truffles',
    description: 'Hand-rolled truffles with South Indian spices and raw West Godavari cacao.',
    category: 'Dessert',
    pricePerHead: 220,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=800&auto=format&fit=crop',
  },

  // 11. Karachi Bakery
  {
    id: 'd_karachi_fruit_biscuits',
    partnerId: 'ptr_karachi',
    partnerName: 'Karachi Bakery',
    name: 'Original Karachi Fruit Biscuits',
    description: 'World-famous crumbly biscuits with candied papaya and cardamom essence.',
    category: 'Dessert',
    pricePerHead: 60,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
  },
];
