/**
 * Curated Fallback Data for Food Tailor (Hyderabad Atelier Guild)
 * Guarantees rich, instant UI rendering across all pages with zero empty states.
 */

export const FALLBACK_PARTNERS = [
  {
    id: 'ptr_niloufer',
    slug: 'cafe-niloufer',
    businessName: 'Cafe Niloufer',
    cuisine: 'Irani & Bakery',
    location: 'Lakdikapul / Banjara Hills',
    description: "Since 1978, Cafe Niloufer has defined Hyderabad's quintessential Irani chai and artisanal bakery culture with scalded whole-milk chai and double-baked Osmania biscuits.",
    coverImageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=1200&auto=format&fit=crop',
    established: 1978,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 2500,
    maxEventCapacity: 500,
    tagline: 'Legacy of Royal Scalded Whole-Milk Irani Chai',
    whyWePicked: 'Quintessential Hyderabadi afternoon gathering tea and biscuit institution with uncompromised whole milk freshness.',
  },
  {
    id: 'ptr_shadab',
    slug: 'hotel-shadab',
    businessName: 'Hotel Shadab',
    cuisine: 'Hyderabadi & Mughlai',
    location: 'Ghansi Bazaar / Old City',
    description: 'Near the historic Charminar since 1953, producing legendary slow-cooked Nizami Mutton Dum Biryani, royal Marag, and saffron-rich Shahi Tukda.',
    coverImageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=1200&auto=format&fit=crop',
    established: 1953,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 5000,
    maxEventCapacity: 1000,
    tagline: 'Imperial Dastarkhwan & Copper Degh Heritage',
    whyWePicked: 'Old City royalty with 70+ years of unyielding master-degh consistency and saffron layering.',
  },
  {
    id: 'ptr_samosasingh',
    slug: 'sammosa-singh',
    businessName: 'Sammosa Singh',
    cuisine: 'Appetizers & Snacks',
    location: 'Hitec City / Gachibowli',
    description: "Reinventing India's king of snacks with proprietary triangular pastries that stay crisp for 45+ minutes in thermal banquet carriers.",
    coverImageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1200&auto=format&fit=crop',
    established: 2016,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 1800,
    maxEventCapacity: 600,
    tagline: 'Cocktail Hour Crispness Engineered for Events',
    whyWePicked: 'Ultra-crisp cocktail starters that retain textural integrity during high-volume banquet service.',
  },
  {
    id: 'ptr_manam',
    slug: 'manam-chocolate',
    businessName: 'Manam Chocolate',
    cuisine: 'Artisanal Confectionery',
    location: 'Road No. 12, Banjara Hills',
    description: 'Award-winning craft chocolate atelier transforming West Godavari single-origin cacao into world-class bonbons, truffles, and tablets.',
    coverImageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=1200&auto=format&fit=crop',
    established: 2022,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3000,
    maxEventCapacity: 300,
    tagline: 'Single-Origin West Godavari Cacao Ateliers',
    whyWePicked: 'World-recognized bean-to-bar craftsmanship from the lush fertile delta of the Godavari.',
  },
  {
    id: 'ptr_almondhouse',
    slug: 'almond-house',
    businessName: 'Almond House',
    cuisine: 'Royal Indian Sweets',
    location: 'Himayatnagar / Jubilee Hills',
    description: 'Master confectioners renowned for pure ghee Bisticks, Badam Halwa, dry-fruit Kaju rolls, and silver-vark Shahi sweets.',
    coverImageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=1200&auto=format&fit=crop',
    established: 1989,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3500,
    maxEventCapacity: 800,
    tagline: 'Pure Ghee Confectionery & Shahi Mithai Masters',
    whyWePicked: 'Unsurpassed pure A2 ghee purity and bespoke silver-vark presentation boxes.',
  },
  {
    id: 'ptr_iceberg',
    slug: 'ice-berg',
    businessName: 'Ice Berg',
    cuisine: 'Desserts & Ice Creams',
    location: 'Jubilee Hills / Madhapur',
    description: 'Organic handcrafted ice creams made with real seasonal fruits like Sitaphal, tender coconut, and organic Alphonso mango.',
    coverImageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?q=80&w=1200&auto=format&fit=crop',
    established: 2012,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 500,
    tagline: 'Organic Real Fruit & Fresh Cream Ateliers',
    whyWePicked: 'Real fruit churns served in frozen coconut shells for spectacular interactive event staging.',
  },
  {
    id: 'ptr_maharaja',
    slug: 'maharaja-chaat',
    businessName: 'Maharaja Chaat',
    cuisine: 'Street Food & Chaat',
    location: 'Madhapur / Jubilee Hills',
    description: 'Hyderabad’s gold standard for live Pani Puri bars, Dahi Puri platters, and sizzling Aloo Tikki chaat counters.',
    coverImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
    established: 2005,
    isApproved: true,
    rating: 4.7,
    minOrderAmount: 2500,
    maxEventCapacity: 600,
    tagline: 'Interactive Royal Street Food Counters',
    whyWePicked: 'Hygienic, vibrant live chaat staging with mineral water and organic chutneys.',
  },
  {
    id: 'ptr_karachi',
    slug: 'karachi-bakery',
    businessName: 'Karachi Bakery',
    cuisine: 'Irani & Bakery',
    location: 'Moazzam Jahi Market / Banjara Hills',
    description: 'The legendary bakery house operating since 1953, famous for fruit biscuits, cashew almond pastries, and artisanal tea cakes.',
    coverImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop',
    established: 1953,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 2000,
    maxEventCapacity: 1000,
    tagline: 'Iconic Hyderabad Heritage Bakery House',
    whyWePicked: 'Celebrated legacy bakes with unmistakable signature flavors.',
  },
  {
    id: 'ptr_pistahouse',
    slug: 'pista-house',
    businessName: 'Pista House',
    cuisine: 'Hyderabadi & Mughlai',
    location: 'Charminar / Gachibowli',
    description: 'Global ambassadors of GI-tagged Hyderabadi Haleem, Zafrani Mutton Biryani, and traditional bakery delicacies.',
    coverImageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop',
    established: 1997,
    isApproved: true,
    rating: 4.8,
    minOrderAmount: 4000,
    maxEventCapacity: 1200,
    tagline: 'GI-Tagged Royal Hyderabadi Haleem Leaders',
    whyWePicked: 'Renowned for world-class GI-tagged Haleem simmered overnight with pure ghee and crushed wheat.',
  },
  {
    id: 'ptr_concu',
    slug: 'concu',
    businessName: 'Conçu',
    cuisine: 'Artisanal Confectionery',
    location: 'Jubilee Hills / Begumpet',
    description: 'European patisserie and boulangerie creating French choux pastries, mille-feuille, entremets, and bespoke tiered celebration cakes.',
    coverImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=1200&auto=format&fit=crop',
    established: 2012,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 3500,
    maxEventCapacity: 400,
    tagline: 'Haute French Patisserie & Celebration Cakes',
    whyWePicked: 'Impeccable French pastry precision and sculptural centerpiece gateaux.',
  },
  {
    id: 'ptr_dimmy',
    slug: 'dimmy-pan-palace',
    businessName: 'Dimmy Pan Palace',
    cuisine: 'Paan & After-Mints',
    location: 'Sindhi Colony / Jubilee Hills',
    description: 'The aristocratic conclusion to royal Hyderabad banquets with chocolate paan, silver-vark meetha paan, and exotic mukhwas.',
    coverImageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
    established: 1990,
    isApproved: true,
    rating: 4.9,
    minOrderAmount: 1500,
    maxEventCapacity: 1500,
    tagline: 'Silver-Vark Royal Digestif Lounges',
    whyWePicked: 'Tobacco-free, gold and silver foil wrapped artisanal digestifs served on chilled brass pedestals.',
  },
];

export const FALLBACK_DISHES = [
  {
    id: 'd_shadab_biryani',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Royal Nizami Mutton Dum Biryani',
    description: 'Aged long-grain basmati rice and tender spring mutton slow-steamed in sealed copper deghs with saffron and royal spices.',
    category: 'Biryani',
    pricePerHead: 320,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_shadab_marag',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Nizami Zafrani Marag',
    description: 'Aromatic mutton broth simmered for 8 hours with cashew almond paste, black pepper, and saffron essence.',
    category: 'Starter',
    pricePerHead: 240,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_shadab_shahitukda',
    partnerId: 'ptr_shadab',
    partnerName: 'Hotel Shadab',
    name: 'Double Ka Meetha (Shahi Tukda)',
    description: 'Crisp ghee-fried milk bread soaked in saffron-infused rabri, topped with slivered pistachios and silver vark.',
    category: 'Dessert',
    pricePerHead: 160,
    isVeg: true,
    isSignature: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_niloufer_chai',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Special Scalded Whole-Milk Irani Chai',
    description: 'Decoction steeped with premium Assam CTC tea blended with thick scalded whole milk served piping hot from brass kettles.',
    category: 'Beverage',
    pricePerHead: 90,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_niloufer_osmania',
    partnerId: 'ptr_niloufer',
    partnerName: 'Cafe Niloufer',
    name: 'Royal Osmania & Maska Cookies Platter',
    description: 'Crispy, sweet-and-savory heritage butter biscuits baked fresh with real butter and a touch of cardamom.',
    category: 'Starter',
    pricePerHead: 110,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_samosa_cocktail',
    partnerId: 'ptr_samosasingh',
    partnerName: 'Sammosa Singh',
    name: 'Gourmet Cocktail Samosa Platter (4 Varietals)',
    description: 'Assortment of Cheese Chilli, Paneer Tikka, Spiced Corn, and Classic Punjabi Potato samosas with mint-tamarind chutneys.',
    category: 'Starter',
    pricePerHead: 180,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_manam_bonbons',
    partnerId: 'ptr_manam',
    partnerName: 'Manam Chocolate',
    name: 'Single-Origin Godavari Cacao Bonbon Box (6 Pcs)',
    description: 'Hand-painted bonbons with fillings of Filter Coffee Ganache, Passionfruit Mango, and Smoked Salted Caramel.',
    category: 'Dessert',
    pricePerHead: 280,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_almond_badamhalwa',
    partnerId: 'ptr_almondhouse',
    partnerName: 'Almond House',
    name: 'Pure Ghee Badam Halwa (Almond Pudding)',
    description: 'Slow-cooked crushed California almonds simmered in pure desi cow ghee, saffron milk, and green cardamom.',
    category: 'Dessert',
    pricePerHead: 220,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_iceberg_sitaphal',
    partnerId: 'ptr_iceberg',
    partnerName: 'Ice Berg',
    name: 'Real Sitaphal & Tender Coconut Scoops',
    description: 'Creamy artisanal ice cream packed with fresh custard apple pulp and tender coconut slivers without artificial essence.',
    category: 'Dessert',
    pricePerHead: 160,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_maharaja_panipuri',
    partnerId: 'ptr_maharaja',
    partnerName: 'Maharaja Chaat',
    name: 'Royal Mineral Water Pani Puri Counter (4 Flavors)',
    description: 'Crispy semolina puris served with mint-coriander spicy water, sweet dates water, hing jaljeera, and spiced potato-chickpea ragda.',
    category: 'Starter',
    pricePerHead: 140,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_pistahouse_haleem',
    partnerId: 'ptr_pistahouse',
    partnerName: 'Pista House',
    name: 'GI-Tagged Shahi Mutton Haleem',
    description: 'Slow-cooked for 12 hours with pounded wheat, shredded tender mutton, pure ghee, and topped with fried onions, cashews, and lemon.',
    category: 'Main',
    pricePerHead: 290,
    isVeg: false,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'd_dimmy_meethapaan',
    partnerId: 'ptr_dimmy',
    partnerName: 'Dimmy Pan Palace',
    name: 'Silver-Vark Shahi Maghai Meetha Paan',
    description: 'Tender Banarasi betel leaf stuffed with gulkand, sweetened fennel, dates, cardamom, and enveloped in 100% vegetarian silver vark.',
    category: 'Paan',
    pricePerHead: 80,
    isVeg: true,
    isSignature: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800&auto=format&fit=crop',
  },
];
